application: newsai-main-site
version: 4
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /feed/
  static_files: public/blog/index.xml
  upload: public/blog/index.xml
- url: /feed
  static_files: public/blog/index.xml
  upload: public/blog/index.xml
- url: /social-sync/?
  static_files: public/social-sync.html
  upload: public/social-sync.html
- url: /pricing/?
  static_files: public/pricing.html
  upload: public/pricing.html
- url: /termsofservice/?
  static_files: public/termsofservice.html
  upload: public/termsofservice.html
- url: /privacy/?
  static_files: public/privacy.html
  upload: public/privacy.html
- url: /blog/feed/
  static_files: public/blog/index.xml
  upload: public/blog/index.xml
- url: /blog/feed
  static_files: public/blog/index.xml
  upload: public/blog/index.xml
- url: /blog/(.*)/$
  static_files: public/blog/\1/index.html
  upload: /blog/.*\.html$
- url: /blog/
  static_files: public/blog/index.html
  upload: public/blog/index.html
- url: /blog
  static_files: public/blog/index.html
  upload: public/blog/index.html
- url: /a/(.*)
  script: main.app
- url: /(.+)
  static_files: public/\1
  upload: public/(.*)
- url: /
  static_files: public/index.html
  upload: public/index.html
- url: /blog/css
  static_dir: public/blog/css
- url: /blog/js
  static_dir: public/blog/js
- url: /blog/images
  static_dir: public/blog/images

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?

libraries:
- name: ssl
  version: latest