baseURL = "/pitchbook"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Docdock"
theme = "docdock"
themesdir = "themes"

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]
